from enum import StrEnum


class LeadState(StrEnum):
    DISCOVERED = "DISCOVERED"
    QUALIFIED = "QUALIFIED"
    LOW_PRIORITY = "LOW_PRIORITY"
    REJECTED = "REJECTED"
    RESEARCH_PENDING = "RESEARCH_PENDING"
    RESEARCHING = "RESEARCHING"
    RESEARCHED = "RESEARCHED"
    CONTACTABLE = "CONTACTABLE"
    NO_CONTACT = "NO_CONTACT"
    SKIPPED = "SKIPPED"


class JobState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    RETRY = "RETRY"
    SKIPPED = "SKIPPED"


class ClaimClass(StrEnum):
    OBSERVED_FACT = "OBSERVED_FACT"
    REASONABLE_INFERENCE = "REASONABLE_INFERENCE"
    UNVERIFIED = "UNVERIFIED"


class WebsiteState(StrEnum):
    LIVE = "LIVE"
    BROKEN = "BROKEN"
    NO_WEBSITE = "NO_WEBSITE"
    SOCIAL_ONLY = "SOCIAL_ONLY"
    PARKED = "PARKED"
    UNCERTAIN = "UNCERTAIN"


class StrategyDecision(StrEnum):
    CONTACT = "CONTACT"
    RESEARCH_MORE = "RESEARCH_MORE"
    LOW_PRIORITY = "LOW_PRIORITY"
    SKIP = "SKIP"


class ApprovalState(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DraftReviewDecision(StrEnum):
    APPROVE = "APPROVE"
    REWRITE = "REWRITE"
    REJECT = "REJECT"


class MessageState(StrEnum):
    DRAFT = "DRAFT"
    QUEUED = "QUEUED"
    SENDING = "SENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ReplyClass(StrEnum):
    POSITIVE = "POSITIVE"
    INTERESTED_BUT_LATER = "INTERESTED_BUT_LATER"
    QUESTION = "QUESTION"
    REFERRAL = "REFERRAL"
    NOT_INTERESTED = "NOT_INTERESTED"
    UNSUBSCRIBE = "UNSUBSCRIBE"
    AUTO_REPLY = "AUTO_REPLY"
    BOUNCE = "BOUNCE"
    UNKNOWN = "UNKNOWN"


class ContactState(StrEnum):
    VERIFIED = "VERIFIED"
    UNCERTAIN = "UNCERTAIN"
    INVALID = "INVALID"


class FollowupState(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    QUEUED = "QUEUED"
    SENT = "SENT"
    CANCELLED = "CANCELLED"
